name = "d1"
main = "src/index.ts"
compatibility_date = "2025-05-05"

account_id = "c72786e48b88e7492830a60584c2ac13"

[[d1_databases]]
binding = "MY_DATABASE"    # i.e. available in the Worker on env.MY_DATABASE
database_name = "d1-sandbox-db"
database_id = "02c7adb9-4962-44f3-af60-f9dbe613bd47"
