name: Lint GitHub Actions workflows
on:
  pull_request:
    paths:
      - '.github/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # see https://github.com/rhysd/actionlint/blob/main/docs/usage.md
      - name: Check workflow files
        # https://hub.docker.com/r/rhysd/actionlint/tags
        uses: docker://rhysd/actionlint:1.7.1
        with:
          # See <https://github.com/rhysd/actionlint/blob/main/docs/usage.md#ignore-some-errors>.
          # We ignore this error because it's a false positive due to a bug in actionlint
          # (https://github.com/rhysd/actionlint/issues/133).
          args: "-ignore 'section must be (sequence|mapping) node but got alias node'"
